# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_resultados.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DesignWindows.imagenes import imagenes_new


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 632)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(37, 93, 126, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo_ventana = QtWidgets.QLabel(self.centralwidget)
        self.titulo_ventana.setGeometry(QtCore.QRect(160, 10, 501, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_ventana.sizePolicy().hasHeightForWidth())
        self.titulo_ventana.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        self.titulo_ventana.setFont(font)
        self.titulo_ventana.setStyleSheet("font: 700 30pt \"Arial Rounded MT\";\n"
"color:Blue")
        self.titulo_ventana.setObjectName("titulo_ventana")
        self.boton_volver = QtWidgets.QPushButton(self.centralwidget)
        self.boton_volver.setGeometry(QtCore.QRect(10, 10, 160, 30))
        self.boton_volver.setStyleSheet("""
    QPushButton {
        background-color: rgb(20, 20, 255);
        font: 700 12pt "Arial Rounded MT";
        color: white;
    }
    QPushButton:hover {
        background-color: rgb(50, 50, 255);
    }
"""     )
        self.boton_volver.setObjectName("boton_volver")
        self.boton_mostrar_diagrama = QtWidgets.QPushButton(self.centralwidget)
        self.boton_mostrar_diagrama.setEnabled(True)
        self.boton_mostrar_diagrama.setGeometry(QtCore.QRect(570, 300, 191, 51))
        self.boton_mostrar_diagrama.setStyleSheet("""
    QPushButton {
        background-color: rgb(20, 20, 255);
        font: 700 12pt "Arial Rounded MT";
        color: white;
    }
    QPushButton:hover {
        background-color: rgb(50, 50, 255);
    }
"""     )
        self.boton_mostrar_diagrama.setObjectName("boton_mostrar_diagrama")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 70, 151, 20))
        self.label.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 700 10pt \"Arial Rounded MT\";")
        self.label.setObjectName("label")
        self.label_algoritmo_escogido = QtWidgets.QLabel(self.centralwidget)
        self.label_algoritmo_escogido.setGeometry(QtCore.QRect(370, 70, 171, 16))
        self.label_algoritmo_escogido.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 12pt \"Algerian\";")
        self.label_algoritmo_escogido.setObjectName("label_algoritmo_escogido")
        self.tabla_tiempos_espera = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_tiempos_espera.setGeometry(QtCore.QRect(30, 100, 221, 421))
        self.tabla_tiempos_espera.setObjectName("tabla_tiempos_espera")
        self.tabla_tiempos_espera.setColumnCount(1)
        self.tabla_tiempos_espera.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_tiempos_espera.setHorizontalHeaderItem(0, item)
        self.tabla_tiempos_espera.horizontalHeader().setDefaultSectionSize(150)
        self.tabla_tiempos_espera.horizontalHeader().setMinimumSectionSize(32)
        self.tabla_tiempos_espera.verticalHeader().setDefaultSectionSize(35)
        self.tabla_tiempos_espera.setStyleSheet("""
        QTableWidget {
            background-color: #222222;   /* Fondo oscuro */
            color: white;               /* Texto en blanco */
            gridline-color: #444444;    /* Color de las líneas de la cuadrícula */
            font: 12pt "Arial";
        }

        QHeaderView::section {
            background-color: #003399;  /* Encabezado un poco más claro */
            color: white;               /* Texto del encabezado en blanco */
            font-weight: bold;          /* Negrita para el encabezado */
            border: 1px solid #555555;
            height: 30px;               /* Altura de cada sección de encabezado */
        }

        QTableCornerButton::section {
            background-color: #0055FF;  /* Botón de la esquina superior izquierda */
            border: 1px solid #555555;
        }

        QTableWidget::item {
            selection-background-color: #555555; /* Color de selección de celdas */
            selection-color: white;
        }
        """)
        self.tabla_tiempos_sistema = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_tiempos_sistema.setGeometry(QtCore.QRect(280, 100, 221, 421))
        self.tabla_tiempos_sistema.setObjectName("tabla_tiempos_sistema")
        self.tabla_tiempos_sistema.setColumnCount(1)
        self.tabla_tiempos_sistema.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_tiempos_sistema.setHorizontalHeaderItem(0, item)
        self.tabla_tiempos_sistema.horizontalHeader().setDefaultSectionSize(150)
        self.tabla_tiempos_sistema.horizontalHeader().setMinimumSectionSize(32)
        self.tabla_tiempos_sistema.verticalHeader().setDefaultSectionSize(35)
        self.tabla_tiempos_sistema.setStyleSheet("""
        QTableWidget {
            background-color: #222222;   /* Fondo oscuro */
            color: white;               /* Texto en blanco */
            gridline-color: #444444;    /* Color de las líneas de la cuadrícula */
            font: 12pt "Arial";
        }

        QHeaderView::section:horizontal {
        background-color: #003399;  /* Azul intenso */
        color: white;               
        font-weight: bold;
        border: 1px solid #555555;
        height: 30px;
        }

        QHeaderView::section:vertical {
        background-color: #003399;  /* Mismo azul para filas */
        color: white;
        font-weight: bold;
        border: 1px solid #555555;
        height: 30px;
        }
        """)
        self.imagen_pulgar = QtWidgets.QLabel(self.centralwidget)
        self.imagen_pulgar.setGeometry(QtCore.QRect(580, 130, 161, 151))
        self.imagen_pulgar.setStyleSheet("image: url(:/icono/icono+pulgar.png);")
        self.imagen_pulgar.setText("")
        self.imagen_pulgar.setObjectName("imagen_pulgar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo_ventana.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">TIEMPOS CALCULADOS</span></p></body></html>"))
        self.boton_volver.setText(_translate("MainWindow", "VOLVER AL MENÚ"))
        self.boton_mostrar_diagrama.setText(_translate("MainWindow", "MOSTRAR DIAGRAMA"))
        self.label.setText(_translate("MainWindow", "CON EL ALGORITMO:"))
        self.label_algoritmo_escogido.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">&quot;ROUND ROBIN&quot;</span></p></body></html>"))
        item = self.tabla_tiempos_espera.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TIEMPOS_DE_ESPERA"))
        item = self.tabla_tiempos_sistema.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TIEMPOS_DE_SISTEMA"))
