# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_tabla.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 632)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(37, 93, 126, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo_ventana = QtWidgets.QLabel(self.centralwidget)
        self.titulo_ventana.setGeometry(QtCore.QRect(120, 10, 631, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_ventana.sizePolicy().hasHeightForWidth())
        self.titulo_ventana.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        self.titulo_ventana.setFont(font)
        self.titulo_ventana.setStyleSheet("font: 700 30pt \"Arial Rounded MT\";\n"
"color:Blue")
        self.titulo_ventana.setObjectName("titulo_ventana")
        self.boton_volver = QtWidgets.QPushButton(self.centralwidget)
        self.boton_volver.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.boton_volver.setStyleSheet("""
    QPushButton {
        background-color: rgb(127, 127, 127);
        color: white;
        font: 700 12pt "Arial Rounded MT";
        border-radius: 5px;
    }
    QPushButton:hover {
        background-color: rgb(180, 180, 180);
    }
"""     )
        self.boton_volver.setObjectName("boton_volver")
        self.boton_simular = QtWidgets.QPushButton(self.centralwidget)
        self.boton_simular.setEnabled(False)
        self.boton_simular.setGeometry(QtCore.QRect(500, 460, 181, 51))
        self.boton_simular.setStyleSheet("""
    QPushButton {
        background-color: rgb(20, 20, 255);
        color: white;
        font: 700 12pt "Arial Rounded MT";
        border-radius: 5px;
    }
    QPushButton:hover {
        background-color: rgb(50, 50, 255);
    }
"""     )
        self.boton_simular.setObjectName("boton_simular")
        self.tabla_procesos = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_procesos.setGeometry(QtCore.QRect(20, 70, 365, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabla_procesos.sizePolicy().hasHeightForWidth())
        self.tabla_procesos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabla_procesos.setFont(font)
        self.tabla_procesos.setStyleSheet("    QTableWidget {\n"
"        background-color: rgb(33, 33, 33);\n"
"        color: white;              /* Texto blanco */\n"
"        gridline-color: black;     /* Líneas blancas */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: rgb(60, 60, 60);\n"
"        color: white;              /* Texto de encabezado en blanco */\n"
"    }\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tabla_procesos.setObjectName("tabla_procesos")
        self.tabla_procesos.setColumnCount(2)
        self.tabla_procesos.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tabla_procesos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tabla_procesos.setHorizontalHeaderItem(1, item)
        self.tabla_procesos.horizontalHeader().setDefaultSectionSize(176)
        self.tabla_procesos.verticalHeader().setDefaultSectionSize(40)
        self.subtitulo_seleccion_algoritmo = QtWidgets.QLabel(self.centralwidget)
        self.subtitulo_seleccion_algoritmo.setGeometry(QtCore.QRect(430, 140, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.subtitulo_seleccion_algoritmo.setFont(font)
        self.subtitulo_seleccion_algoritmo.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 700 12pt \"Arial Rounded MT\";")
        self.subtitulo_seleccion_algoritmo.setObjectName("subtitulo_seleccion_algoritmo")
        self.seleccionador_algoritmo = QtWidgets.QComboBox(self.centralwidget)
        self.seleccionador_algoritmo.setGeometry(QtCore.QRect(520, 210, 141, 24))
        self.seleccionador_algoritmo.setObjectName("seleccionador_algoritmo")
        self.seleccionador_algoritmo.addItem("")
        self.seleccionador_algoritmo.addItem("")
        self.seleccionador_algoritmo.addItem("")
        self.boton_seleccionar_algoritmo = QtWidgets.QPushButton(self.centralwidget)
        self.boton_seleccionar_algoritmo.setEnabled(True)
        self.boton_seleccionar_algoritmo.setGeometry(QtCore.QRect(520, 240, 141, 31))
        self.boton_seleccionar_algoritmo.setStyleSheet("""
    QPushButton {
        background-color: rgb(154, 154, 154);
        color: black;
        font: 700 7pt "Arial Rounded MT";
        border-radius: 5px;
    }
    QPushButton:hover {
        background-color: rgb(180, 180, 180);
    }
"""     )
        self.boton_seleccionar_algoritmo.setObjectName("boton_seleccionar_algoritmo")
        self.subtitulo_quantum = QtWidgets.QLabel(self.centralwidget)
        self.subtitulo_quantum.setVisible(False)
        self.subtitulo_quantum.setGeometry(QtCore.QRect(480, 300, 221, 41))
        self.subtitulo_quantum.setStyleSheet("color: rgb(0, 0, 255);")
        self.subtitulo_quantum.setObjectName("subtitulo_quantum")
        self.seleccionador_quantum = QtWidgets.QComboBox(self.centralwidget)
        self.seleccionador_quantum.setVisible(False)
        self.seleccionador_quantum.setGeometry(QtCore.QRect(520, 350, 141, 24))
        self.seleccionador_quantum.setObjectName("seleccionador_quantum")
        self.seleccionador_quantum.addItem("")
        self.seleccionador_quantum.addItem("")
        self.seleccionador_quantum.addItem("")
        self.seleccionador_quantum.addItem("")
        self.seleccionador_quantum.addItem("")
        self.seleccionador_quantum.addItem("")
        self.seleccionador_quantum.addItem("")
        self.seleccionador_quantum.addItem("")
        self.seleccionador_quantum.addItem("")
        self.seleccionador_quantum.addItem("")
        self.boton_seleccionar_quantum = QtWidgets.QPushButton(self.centralwidget)
        self.boton_seleccionar_quantum.setVisible(False)
        self.boton_seleccionar_quantum.setGeometry(QtCore.QRect(520, 380, 141, 31))
        self.boton_seleccionar_quantum.setStyleSheet("""
    QPushButton {
        background-color: rgb(154, 154, 154);
        color: black;
        font: 700 7pt "Arial Rounded MT";
        border-radius: 5px;
    }
    QPushButton:hover {
        background-color: rgb(180, 180, 180);
    }
"""     )
        self.boton_seleccionar_quantum.setObjectName("boton_seleccionar_quantum")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo_ventana.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">INFORMACION DE PROCESOS</p></body></html>"))
        self.boton_volver.setText(_translate("MainWindow", "VOLVER"))
        self.boton_simular.setText(_translate("MainWindow", "SIMULAR"))
        self.tabla_procesos.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabla_procesos.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        item = self.tabla_procesos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RAFAGA_CPU"))
        item = self.tabla_procesos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TIEMPO_LLEGADA_COLA"))
        self.subtitulo_seleccion_algoritmo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">SELECCIONE EL ALGORITMO</span></p><p align=\"center\"><span style=\" font-style:italic;\">QUE DESEA UTILIZAR</span></p></body></html>"))
        self.seleccionador_algoritmo.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.seleccionador_algoritmo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.seleccionador_algoritmo.setItemText(0, _translate("MainWindow", "FIFO"))
        self.seleccionador_algoritmo.setItemText(1, _translate("MainWindow", "SJF"))
        self.seleccionador_algoritmo.setItemText(2, _translate("MainWindow", "ROUND ROBIN"))
        self.boton_seleccionar_algoritmo.setText(_translate("MainWindow", "SELECCIONAR"))
        self.subtitulo_quantum.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">SELECCIONE EL QUANTUM</span></p><p align=\"center\"><span style=\" font-style:italic;\">QUE DESEA ASIGNAR</span></p></body></html>"))
        self.seleccionador_quantum.setItemText(0, _translate("MainWindow", "1"))
        self.seleccionador_quantum.setItemText(1, _translate("MainWindow", "2"))
        self.seleccionador_quantum.setItemText(2, _translate("MainWindow", "3"))
        self.seleccionador_quantum.setItemText(3, _translate("MainWindow", "4"))
        self.seleccionador_quantum.setItemText(4, _translate("MainWindow", "5"))
        self.seleccionador_quantum.setItemText(5, _translate("MainWindow", "6"))
        self.seleccionador_quantum.setItemText(6, _translate("MainWindow", "7"))
        self.seleccionador_quantum.setItemText(7, _translate("MainWindow", "8"))
        self.seleccionador_quantum.setItemText(8, _translate("MainWindow", "9"))
        self.seleccionador_quantum.setItemText(9, _translate("MainWindow", "10"))
        self.boton_seleccionar_quantum.setText(_translate("MainWindow", "SELECCIONAR"))
