# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_calculo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 632)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(37, 93, 126, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo_ventana = QtWidgets.QLabel(self.centralwidget)
        self.titulo_ventana.setGeometry(QtCore.QRect(110, 10, 621, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_ventana.sizePolicy().hasHeightForWidth())
        self.titulo_ventana.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.titulo_ventana.setFont(font)
        self.titulo_ventana.setStyleSheet("font: 700 30pt \"Arial Rounded MT\";\n"
"color:Blue")
        self.titulo_ventana.setObjectName("titulo_ventana")
        self.boton_volver = QtWidgets.QPushButton(self.centralwidget)
        self.boton_volver.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.boton_volver.setStyleSheet("background-color: rgb(127, 127, 127);")
        self.boton_volver.setObjectName("boton_volver")
        self.boton_calcular_algoritmo = QtWidgets.QPushButton(self.centralwidget)
        self.boton_calcular_algoritmo.setEnabled(True)
        self.boton_calcular_algoritmo.setGeometry(QtCore.QRect(300, 500, 221, 51))
        self.boton_calcular_algoritmo.setStyleSheet("background-color: rgb(20, 20, 255);\n"
"font: 700 12pt \"Arial Rounded MT\";")
        self.boton_calcular_algoritmo.setObjectName("boton_calcular_algoritmo")
        self.imagen_pulgar = QtWidgets.QLabel(self.centralwidget)
        self.imagen_pulgar.setGeometry(QtCore.QRect(640, 360, 161, 151))
        self.imagen_pulgar.setStyleSheet("image: url(:/icono/icono+pulgar.png);")
        self.imagen_pulgar.setText("")
        self.imagen_pulgar.setObjectName("imagen_pulgar")
        self.subtitulo_lista_paginas = QtWidgets.QLabel(self.centralwidget)
        self.subtitulo_lista_paginas.setGeometry(QtCore.QRect(220, 80, 381, 20))
        self.subtitulo_lista_paginas.setStyleSheet("color: rgb(0, 0, 77);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.subtitulo_lista_paginas.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitulo_lista_paginas.setObjectName("subtitulo_lista_paginas")
        self.label_marcos = QtWidgets.QLabel(self.centralwidget)
        self.label_marcos.setGeometry(QtCore.QRect(120, 230, 581, 20))
        self.label_marcos.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.label_marcos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_marcos.setObjectName("label_marcos")
        self.ingresar_marcos = QtWidgets.QLineEdit(self.centralwidget)
        self.ingresar_marcos.setGeometry(QtCore.QRect(350, 250, 113, 20))
        self.ingresar_marcos.setStyleSheet("background-color: rgb(152, 152, 152);\n"
"font: 8pt \"Arial Rounded MT Bold\";\n"
"")
        self.ingresar_marcos.setAlignment(QtCore.Qt.AlignCenter)
        self.ingresar_marcos.setObjectName("ingresar_marcos")
        self.label_escoger_algoritmo = QtWidgets.QLabel(self.centralwidget)
        self.label_escoger_algoritmo.setGeometry(QtCore.QRect(260, 370, 301, 20))
        self.label_escoger_algoritmo.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.label_escoger_algoritmo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_escoger_algoritmo.setObjectName("label_escoger_algoritmo")
        self.boton_confirmar_marcos = QtWidgets.QPushButton(self.centralwidget)
        self.boton_confirmar_marcos.setEnabled(True)
        self.boton_confirmar_marcos.setGeometry(QtCore.QRect(300, 280, 221, 31))
        self.boton_confirmar_marcos.setStyleSheet("background-color: rgb(20, 20, 255);\n"
"font: 700 8pt \"Arial Rounded MT\";")
        self.boton_confirmar_marcos.setObjectName("boton_confirmar_marcos")
        self.seleccionar_algoritmo = QtWidgets.QComboBox(self.centralwidget)
        self.seleccionar_algoritmo.setGeometry(QtCore.QRect(350, 390, 121, 22))
        self.seleccionar_algoritmo.setStyleSheet("background-color: rgb(165, 165, 165);\n"
"")
        self.seleccionar_algoritmo.setObjectName("seleccionar_algoritmo")
        self.seleccionar_algoritmo.addItem("")
        self.seleccionar_algoritmo.addItem("")
        self.seleccionar_algoritmo.addItem("")
        self.seleccionar_algoritmo.addItem("")
        self.boton_confirmar_algoritmo = QtWidgets.QPushButton(self.centralwidget)
        self.boton_confirmar_algoritmo.setEnabled(True)
        self.boton_confirmar_algoritmo.setGeometry(QtCore.QRect(330, 420, 151, 31))
        self.boton_confirmar_algoritmo.setStyleSheet("background-color: rgb(20, 20, 255);\n"
"font: 700 8pt \"Arial Rounded MT\";")
        self.boton_confirmar_algoritmo.setObjectName("boton_confirmar_algoritmo")
        self.tabla_referencias = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_referencias.setGeometry(QtCore.QRect(20, 120, 761, 71))
        self.tabla_referencias.setStyleSheet("background-color: rgb(52, 52, 52);")
        self.tabla_referencias.setObjectName("tabla_referencias")
        self.tabla_referencias.setColumnCount(0)
        self.tabla_referencias.setRowCount(0)
        self.tabla_referencias.horizontalHeader().setDefaultSectionSize(39)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo_ventana.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">IMPLEMENTAR ALGORITMOS</p></body></html>"))
        self.boton_volver.setText(_translate("MainWindow", "VOLVER"))
        self.boton_calcular_algoritmo.setText(_translate("MainWindow", "MOSTRAR ALGORITMO"))
        self.subtitulo_lista_paginas.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.subtitulo_lista_paginas.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.subtitulo_lista_paginas.setText(_translate("MainWindow", "LISTA DE REFERENCIA DE PAGINAS"))
        self.label_marcos.setText(_translate("MainWindow", "DIGITE EL NÚMERO DE MARCOS QUE DESEA PARA CALCULAR EL ALGORITMO"))
        self.ingresar_marcos.setText(_translate("MainWindow", "3"))
        self.label_escoger_algoritmo.setText(_translate("MainWindow", "Elija el algoritmo que desea mostrar"))
        self.boton_confirmar_marcos.setText(_translate("MainWindow", "CONFIRMAR NUMERO DE MARCOS"))
        self.seleccionar_algoritmo.setItemText(0, _translate("MainWindow", "FIFO"))
        self.seleccionar_algoritmo.setItemText(1, _translate("MainWindow", "LRU"))
        self.seleccionar_algoritmo.setItemText(2, _translate("MainWindow", "OPTIMO"))
        self.seleccionar_algoritmo.setItemText(3, _translate("MainWindow", "FIFO MEJORADO"))
        self.boton_confirmar_algoritmo.setText(_translate("MainWindow", "CONFIRMAR ALGORITMO"))
from DesignWindows.imagenes import imagenes_new
