# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(37, 93, 126, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo_ventana = QtWidgets.QLabel(self.centralwidget)
        self.titulo_ventana.setGeometry(QtCore.QRect(80, 30, 631, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_ventana.sizePolicy().hasHeightForWidth())
        self.titulo_ventana.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.titulo_ventana.setFont(font)
        self.titulo_ventana.setStyleSheet("font: 700 12pt \"Arial Rounded MT\";\n"
"color:Blue")
        self.titulo_ventana.setObjectName("titulo_ventana")
        self.boton_salir = QtWidgets.QPushButton(self.centralwidget)
        self.boton_salir.setGeometry(QtCore.QRect(700, 510, 81, 31))
        self.boton_salir.setStyleSheet("background-color: rgb(127, 127, 127);")
        self.boton_salir.setObjectName("boton_salir")
        self.boton_siguiente = QtWidgets.QPushButton(self.centralwidget)
        self.boton_siguiente.setGeometry(QtCore.QRect(310, 410, 181, 51))
        self.boton_siguiente.setStyleSheet("background-color: rgb(20, 20, 255);\n"
"font: 700 12pt \"Arial Rounded MT\";")
        self.boton_siguiente.setObjectName("boton_siguiente")
        self.icono_windows = QtWidgets.QLabel(self.centralwidget)
        self.icono_windows.setGeometry(QtCore.QRect(350, 110, 101, 131))
        self.icono_windows.setStyleSheet("image: url(:/icono/icono+windows3.png);")
        self.icono_windows.setText("")
        self.icono_windows.setObjectName("icono_windows")
        self.icono_apple = QtWidgets.QLabel(self.centralwidget)
        self.icono_apple.setGeometry(QtCore.QRect(170, 120, 101, 111))
        self.icono_apple.setStyleSheet("image: url(:/icono/icono+apple.png);")
        self.icono_apple.setText("")
        self.icono_apple.setObjectName("icono_apple")
        self.icono_linux = QtWidgets.QLabel(self.centralwidget)
        self.icono_linux.setGeometry(QtCore.QRect(510, 120, 101, 111))
        self.icono_linux.setStyleSheet("image: url(:/icono/icono+linux2.png);")
        self.icono_linux.setText("")
        self.icono_linux.setObjectName("icono_linux")
        self.label_FIFO = QtWidgets.QLabel(self.centralwidget)
        self.label_FIFO.setGeometry(QtCore.QRect(40, 110, 71, 31))
        self.label_FIFO.setStyleSheet("font: 700 16pt \"Times New Roman\";\n"
"color:Red;")
        self.label_FIFO.setObjectName("label_FIFO")
        self.label_LRU = QtWidgets.QLabel(self.centralwidget)
        self.label_LRU.setGeometry(QtCore.QRect(40, 140, 71, 31))
        self.label_LRU.setStyleSheet("font: 700 16pt \"Times New Roman\";\n"
"color:Green;")
        self.label_LRU.setObjectName("label_LRU")
        self.subtitulo_procesos_a_simular = QtWidgets.QLabel(self.centralwidget)
        self.subtitulo_procesos_a_simular.setGeometry(QtCore.QRect(160, 250, 491, 91))
        self.subtitulo_procesos_a_simular.setStyleSheet("font: 700 21pt \"Times New Roman\";\n"
"color:Blue;")
        self.subtitulo_procesos_a_simular.setObjectName("subtitulo_procesos_a_simular")
        self.label_OPTIMO = QtWidgets.QLabel(self.centralwidget)
        self.label_OPTIMO.setGeometry(QtCore.QRect(20, 170, 111, 31))
        self.label_OPTIMO.setStyleSheet("font: 700 16pt \"Times New Roman\";\n"
"color:Blue;")
        self.label_OPTIMO.setObjectName("label_OPTIMO")
        self.label_FIFO_MEJORADO = QtWidgets.QLabel(self.centralwidget)
        self.label_FIFO_MEJORADO.setGeometry(QtCore.QRect(40, 200, 71, 31))
        self.label_FIFO_MEJORADO.setStyleSheet("font: 700 16pt \"Times New Roman\";\n"
"color: rgb(255, 8, 251);")
        self.label_FIFO_MEJORADO.setObjectName("label_FIFO_MEJORADO")
        self.campo_ingresar_cadena = QtWidgets.QLineEdit(self.centralwidget)
        self.campo_ingresar_cadena.setGeometry(QtCore.QRect(140, 350, 541, 41))
        self.campo_ingresar_cadena.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.campo_ingresar_cadena.setStyleSheet("background-color: rgb(39, 39, 39);\n"
"font: 63 16pt \"Cascadia Mono SemiBold\";\n"
"color: rgb(255, 255, 255);")
        self.campo_ingresar_cadena.setAlignment(QtCore.Qt.AlignCenter)
        self.campo_ingresar_cadena.setObjectName("campo_ingresar_cadena")
        self.titulo_ventana.raise_()
        self.boton_salir.raise_()
        self.boton_siguiente.raise_()
        self.subtitulo_procesos_a_simular.raise_()
        self.icono_windows.raise_()
        self.icono_apple.raise_()
        self.icono_linux.raise_()
        self.label_FIFO.raise_()
        self.label_LRU.raise_()
        self.label_OPTIMO.raise_()
        self.label_FIFO_MEJORADO.raise_()
        self.campo_ingresar_cadena.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo_ventana.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-style:italic;\">ALGORITMOS DE REMPLAZO</span></p><p align=\"center\"><span style=\" font-size:14pt; font-style:italic;\">DE PAGINAS</span></p></body></html>"))
        self.boton_salir.setText(_translate("MainWindow", "SALIR"))
        self.boton_siguiente.setText(_translate("MainWindow", "SIGUIENTE"))
        self.label_FIFO.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_FIFO.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">FIFO</span></p></body></html>"))
        self.label_LRU.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_LRU.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">LRU</p></body></html>"))
        self.subtitulo_procesos_a_simular.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Ingrese una cadena sin espacios que</p><p align=\"center\"> simule las paginas que están entrando</p></body></html>"))
        self.label_OPTIMO.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_OPTIMO.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">OPTIMO</p></body></html>"))
        self.label_FIFO_MEJORADO.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_FIFO_MEJORADO.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">FIFO +</span></p></body></html>"))
        self.campo_ingresar_cadena.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.campo_ingresar_cadena.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.campo_ingresar_cadena.setText(_translate("MainWindow", "23235388262434727364"))
        
from DesignWindows.imagenes import imagenes_new
