# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_resultados.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 632)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(37, 93, 126, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo_ventana = QtWidgets.QLabel(self.centralwidget)
        self.titulo_ventana.setGeometry(QtCore.QRect(110, 10, 631, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_ventana.sizePolicy().hasHeightForWidth())
        self.titulo_ventana.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.titulo_ventana.setFont(font)
        self.titulo_ventana.setStyleSheet("font: 700 30pt \"Arial Rounded MT\";\n"
"color:Blue")
        self.titulo_ventana.setObjectName("titulo_ventana")
        self.boton_volver = QtWidgets.QPushButton(self.centralwidget)
        self.boton_volver.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.boton_volver.setStyleSheet("background-color: rgb(127, 127, 127);")
        self.boton_volver.setObjectName("boton_volver")
        self.subtitulo_algoritmo_seleccionado = QtWidgets.QLabel(self.centralwidget)
        self.subtitulo_algoritmo_seleccionado.setEnabled(False)
        self.subtitulo_algoritmo_seleccionado.setGeometry(QtCore.QRect(230, 70, 381, 31))
        self.subtitulo_algoritmo_seleccionado.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 57 9pt \"Engravers MT\";")
        self.subtitulo_algoritmo_seleccionado.setObjectName("subtitulo_algoritmo_seleccionado")
        self.label_numero_fallos = QtWidgets.QLabel(self.centralwidget)
        self.label_numero_fallos.setEnabled(False)
        self.label_numero_fallos.setGeometry(QtCore.QRect(230, 540, 381, 31))
        self.label_numero_fallos.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 12pt \"System\";")
        self.label_numero_fallos.setObjectName("label_numero_fallos")
        self.matriz_resultados = QtWidgets.QTableWidget(self.centralwidget)
        self.matriz_resultados.setGeometry(QtCore.QRect(20, 110, 771, 381))
        self.matriz_resultados.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.matriz_resultados.setObjectName("matriz_resultados")
        self.matriz_resultados.setColumnCount(0)
        self.matriz_resultados.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo_ventana.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titulo_ventana.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">MATRIZ DE RESULTADOS</p></body></html>"))
        self.boton_volver.setText(_translate("MainWindow", "VOLVER"))
        self.subtitulo_algoritmo_seleccionado.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ALGORITMO SELECCIONADO: FIFO</p></body></html>"))
        self.label_numero_fallos.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">NUMERO DE FALLOS: X</p></body></html>"))

